### ISSUE TITLE
Build services for Airlines

### ISSUE THREAD

**Issue by hampgoodwin** [abelgoodwin1988/IATA-FINDER#13]

**Comment by JacobSNGoodwin** [comment]
I'll start implementing this next. It should be straightforward as it's similar to the airport services.

@abelgoodwin1988, Does it make sense to have an rpc to search by name, or is entering a name too long, and error prone? Perhaps since airline names can be long (and airports), the rpc could take in a part of a string or a regex. I'm just not sure if that's over doing it for an API.

We certainly need GetAirlines(...), GetAirlineIATA(...), and GetAirlineICAO(...)

**Comment by hampgoodwin** [comment]
I swear I responded to this last night but I guess not.

I think it makes sense, but that is fulfilled by the "GetAirports" or "GetAirlines" rpc which takes a "descriptor". We then will do a strings.contains() for now against any string fields where we thing it's useful. It was just implemented here
https://github.com/abelgoodwin1988/iata-finder/blob/1365d8dcfde9a83a1a30c32426bc26991edd4dc8/main.go#L86-L96
So I imagine something similar for airlines.
